
<LogoScreen>:
	canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'data/fondos/logo_wallpaper.jpg'

    LogoAnimation:

<PaintScreen>:

<IdleScreen>:
	canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'data/fondos/idle_wallpaper.jpg'


<MainScreen>:

	canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'data/fondos/main_wallpaper.jpg'



